services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      target: app
    image: monaa-lisa-app:latest
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      SEMANTIC_SCHOLAR_API_KEY: ${SEMANTIC_SCHOLAR_API_KEY:-}
    volumes:
      - ./MonaaLisa/src:/app/MonaaLisa/src
      - python_cache:/root/.cache/pip
    command: ["/bin/sh", "-c", "export PYTHONPATH=/app/MonaaLisa/src && python MonaaLisa/src/Database/db.py && python MonaaLisa/src/main.py"]

  backend:
    image: node:20
    working_dir: /app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      PORT: 3000
    volumes:
      - ./MonaaLisa/src/Backend:/app
      - backend_node_modules:/app/node_modules
    command: ["sh", "-c", "npm install && npm run build && npm run start:prod"]
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  playground:
    build:
      context: .
      target: app
    image: monaa-lisa-app:latest
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      PYTHONPATH: /app/MonaaLisa/src
      SEMANTIC_SCHOLAR_API_KEY: ${SEMANTIC_SCHOLAR_API_KEY:-}
    volumes:
      - ./MonaaLisa/src:/app/MonaaLisa/src
    working_dir: /app
    profiles:
      - playground
    command: [ "python", "MonaaLisa/src/playground/playground_manager.py" ]

  frontend:
    build:
      context: ./MonaaLisa/src/Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - app
      - backend
    volumes:
      - ./MonaaLisa/src/Frontend:/app
      - /app/node_modules
    environment:
      VITE_API_URL: "http://backend:3000"

  grobid:
    image: lfoppiano/grobid:latest-develop
    ports:
      - "8070:8070"
    depends_on:
      - app
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8070/api/isalive" ]
      interval: 30s
      timeout: 10s
      retries: 5
    
volumes:
  pgdata:
  python_cache:
  backend_node_modules:
