version: "3.9"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-monaa}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secretpassword}
      POSTGRES_DB: ${POSTGRES_DB:-monaa_lisa}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER:-monaa}:${POSTGRES_PASSWORD:-secretpassword}@db:5432/${POSTGRES_DB:-monaa_lisa}
    volumes:
      - .:/app
    command: ["python", "MonaaLisa/src/main.py"]

  frontend:
    build:
      context: ./MonaaLisa/src/Frontend
    ports:
      - "5173:5173"
    depends_on:
      - app
    volumes:
      - ./MonaaLisa/src/Frontend:/app
    environment:
      VITE_API_URL: "http://app:5000"
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]

    
volumes:
  pgdata: