import os
import threading
from pathlib import Path
from typing import Dict, Iterable, Optional

import joblib
import numpy as np
import umap

from object.embedding import Embedding
from util.logger import Logger
from config import cfg

"""
14 Dec 2025 - Basti
In short - what does this class do? Why is it here? What the hell is a UMAP or a Reducer?

This class serves the purpose of reducing high-dimensional embedding vectors generated by our language transformer model 
into a 2D space using UMAP instead of tSNE.

UMAP is a improved version of tSNE, that is faster, scales better with larger datasets and preserves more of the global structure of the data.
tSNE was fine but out old implementation handled the logic/use-case wrong, we needed to migrate anyway in the long term -> thus UMAP it is now

What does UMAP do compared to tSNE?

First off: tSNE works like this: Embeddings that are close to each other in the high dimensional space are mapped to points that are close to each other in the 2D space.
Makes sense -> what is close in the whatever-dimensional space should also be close in the 2D space.
However tSNE has some issues:
- It focuses too much on preserving local structure, which can lead to loss of global relationships between clusters.
- It can be computationally intensive and slow, especially with larger datasets. (O  (N^2) complexity)
- The results can vary significantly with different runs due to its stochastic nature.

UMAP, on the other hand addresses some of these issues:
- It balances the preservation of local and global structure better than tSNE.
- It is generally faster and more scalable to larger datasets (O(N log N) complexity).
- It provides more consistent results across different runs.

=> I could also talk what the issue was with the old implementation we had, because that is tSNE unrelated, was more of our mistake, but it is resolved now. Forget about it.

Why is this class necessary?

This class encapsulates the UMAP reducer logic, ensuring that we have a single shared UMAP model that can be used across multiple paper processing threads.
It handles the fitting of the UMAP model when enough embeddings are available, transforming new embeddings into
2D coordinates, and refitting the model as new embeddings are added to ensure the projections remain accurate and meaningful.

With this class, we can efficiently manage the UMAP reducer's lifecycle, ensuring that our paper visualizations are both accurate and performant.
"""


class UMAPReducer:

    
    def __init__(self):
        self.logger = Logger("UMAPReducer")
        self._lock = threading.Lock()
        self._fit_lock = threading.Lock()
        self._reducer: Optional[umap.UMAP] = None
        self._refit_thread: Optional[threading.Thread] = None
        self._last_fit_count = 0
        self.min_fit_samples = cfg.get_int(
            "semanticpaper",
            "umap_min_fit_samples",
            int(os.getenv("UMAP_MIN_FIT_SAMPLES", "25"))
        )
        self.refit_growth = cfg.get_int(
            "semanticpaper",
            "umap_refit_growth",
            int(os.getenv("UMAP_REFIT_GROWTH", "200"))
        )
        self.model_path = Path(os.getenv("UMAP_MODEL_PATH", "/app/.cache/umap_model.joblib"))
        self.model_path.parent.mkdir(parents=True, exist_ok=True)
        self._load_model_from_disk()

    def _load_model_from_disk(self) -> None:
        if not self.model_path.exists():
            return
        try:
            reducer = joblib.load(self.model_path)
            if isinstance(reducer, umap.UMAP):
                self._reducer = reducer
                self.logger.info("Loaded persisted UMAP reducer from %s", self.model_path)
        except Exception as exc:
            self.logger.warning("Failed to load cached UMAP reducer: %s", exc)

# Update - Basti - 22-December-2025 updated the function signature to accept labels for supervised UMAP

    def bootstrap(self, embeddings: Dict[str, Embedding], labels: Dict[str, str] | None = None):
        self._ensure_reducer(embeddings.values(), labels)

    def has_model(self) -> bool:
        with self._lock:
            return self._reducer is not None

    def transform(self, embedding: Embedding, embeddings: Dict[str, Embedding], labels: Dict[str, str] | None = None):
        reducer = self._ensure_reducer(embeddings.values(), labels)
        if reducer is None:
            return None
        vector = np.asarray(embedding.content, dtype=np.float32).reshape(1, -1)
        try:
            with self._fit_lock:
                coords = reducer.transform(vector)
            return coords[0].tolist()
        except Exception as exc:
            self.logger.error("UMAP transform failed: %s", exc)
            return None

    def notify_dataset_change(self, embeddings: Dict[str, Embedding], labels: Dict[str, str] | None = None):
        """Called after a new embedding has been persisted to consider refitting."""
        total = len(embeddings)
        if total < self.min_fit_samples:
            return
        with self._lock:
            needs_initial_fit = self._reducer is None
            needs_growth_refit = (
                self._reducer is not None
                and total - self._last_fit_count >= self.refit_growth
            )
            if needs_initial_fit:
                self.logger.info("Fitting initial UMAP reducer on %s embeddings", total)
                self._fit_reducer(list(embeddings.values()), labels)
                return
            if not needs_growth_refit:
                return
            if self._refit_thread and self._refit_thread.is_alive():
                return
            self._refit_thread = threading.Thread(
                target=self._fit_reducer,
                args=(list(embeddings.values()), labels),
                daemon=True,
            )
            self._refit_thread.start()

    def _ensure_reducer(self, embeddings: Iterable[Embedding], labels: Dict[str, str] | None = None):
        with self._lock:
            if self._reducer is not None:
                return self._reducer
        embeddings_list = list(embeddings)
        if len(embeddings_list) < self.min_fit_samples:
            self.logger.debug(
                f"Not enough embeddings ({len(embeddings_list)}/{self.min_fit_samples}) to fit UMAP yet"
            )
            return None
        self.logger.info(f"Fitting UMAP reducer on {len(embeddings_list)} embeddings")
        self._fit_reducer(embeddings_list, labels)
        with self._lock:
            return self._reducer

    def _fit_reducer(self, embeddings: list[Embedding], labels: Dict[str, str] | None = None):
        with self._fit_lock:
            with self._lock:
                if self._reducer is not None and len(embeddings) <= self._last_fit_count:
                    return
            vectors, y = self._to_matrix(embeddings, labels)
            if vectors is None:
                return
            reducer = umap.UMAP(
                n_components=2,
                metric="cosine",
                n_neighbors=15,
                min_dist=0.1,
                target_weight=0.5, 
                random_state=42,
                transform_seed=42,
            )
            if y is not None:
                # UMAP expects numeric labels or encoded strings, but sometimes fails with raw strings
                # We encode the string labels to integers for safety
                from sklearn.preprocessing import LabelEncoder
                le = LabelEncoder()
                y_encoded = le.fit_transform(y)
                reducer.fit(vectors, y=y_encoded)
            else:
                reducer.fit(vectors)
            with self._lock:
                self._reducer = reducer
                self._last_fit_count = vectors.shape[0]
                try:
                    joblib.dump(reducer, self.model_path)
                except Exception as exc:
                    self.logger.warning(f"Failed to persist UMAP reducer: {exc}")

    """ 22-Dec-2025 - Basti
    Abstract: Converts a list of Embedding objects to a matrix suitable for UMAP fitting.
    Args:
    - embeddings: Iterable[Embedding] -> The embeddings to convert.
    - labels: Dict[str, str] | None -> Optional labels for supervised UMAP.
    Returns: Tuple (matrix, y) where matrix is a 2D numpy array of embedding
    vectors and y is a list of labels or None.
    """
    def _to_matrix(self, embeddings: Iterable[Embedding], labels: Dict[str, str] | None):
        vectors = []
        y: list[str] = []

        if labels:
            for emb in embeddings:
                label = labels.get(emb.belonging_paper_entry_id)
                if label is None:
                    continue
                vectors.append(np.asarray(emb.content, dtype=np.float32))
                y.append(label)
            if len(vectors) < self.min_fit_samples:
                # Fall back to unsupervised if we do not have enough labeled samples
                self.logger.debug(
                    f"Not enough labeled embeddings ({len(vectors)}/{self.min_fit_samples}); falling back to unsupervised UMAP"
                )
                vectors.clear()
                y.clear()

        if not vectors:
            for emb in embeddings:
                if emb.content is None:
                    continue
                vectors.append(np.asarray(emb.content, dtype=np.float32))

        if len(vectors) < self.min_fit_samples:
            self.logger.debug(
                f"UMAP fit aborted, need at least {self.min_fit_samples} embeddings (have {len(vectors)})"
            )
            return None, None

        matrix = np.vstack(vectors)
        if labels and y and len(y) == len(vectors):
            return matrix, y
        return matrix, None