name: Check PR Rules

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check if branch name is valid
            # Valid Branch Names are the following:
            # feat/
            # feature/
            # fix/
            # hotfix/
            # bugfix/
            # release/
            # chore/
            # cleanup/
            # Please check out the organization for more details.
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          echo "Current Branch Name: $BRANCH_NAME"

          if [[ ! "$BRANCH_NAME" =~ ^(feat|feature|fix|hotfix|bugfix|release|chore|cleanup)/[a-zA-Z0-9._-]+$ ]]; then
            echo "::error::❌ Invalid branch name: '$BRANCH_NAME'"
            echo "✅ Valid formats: feat/*, feature/*, fix/*, hotfix/*, bugfix/*, release/*, chore/*, cleanup/*"
            exit 1
          else
            echo "✅ Branch name '$BRANCH_NAME' is valid."
          fi
        
